# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 2.0.4
maven_group = net.combat_roll
archives_name = combat_roll
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.3

# Dependencies
fabric_loader_version = 0.16.3
fabric_api_version = 0.103.0+1.21.1
neoforge_version = 21.1.1
yarn_mappings_patch_neoforge_version = 1.21+build.4

cloth_config_version=15.0.130
player_anim_version=2.0.0-alpha1+1.21
tiny_config_version=2.3.2

# Compatibility
mod_menu_version=11.0.0
better_combat_version=2.0.0+1.21.1